/*
 * Copyright (c) 2017 Liming Shao <lmshao@163.com>
 */

#include "AudioEncoding.h"

int main()
{
    AudioEncoding audioEncoding;

    // use the pcm file generated by decoding mp3 file as input
    const char *inFile = "../assets/out_s16le.pcm";
    const char *outFile = "../assets/Out.mp3";

    audioEncoding.init();

    // Configure AVCodecContext parameters Manually
    audioEncoding.initCodecContext();

    audioEncoding.readFrameProc(inFile, outFile);
}