/*
* Copyright (c) 2017 Liming Shao <lmshao@163.com>
*/

#include "VideoEncoding.h"

int main()
{
    VideoEncoding videoEncoding;

    // Using the .yuv file generated by the VideoDecoder project 
    const char *inFile = "../assets/Sample_1280x534_yuv420p.yuv";
    const char *outFile = "../assets/Sample1.h264";

    videoEncoding.init();

    // Configure AVCodecContext parameters Manually
    videoEncoding.initCodecContext();

    videoEncoding.readFrameProc(inFile, outFile);

}